/*
This file contains all constants in the app.
*/

const C = {
	// ACTION TYPES
	CHANGE_DISTINCTIVE: "CHANGE_DISTINCTIVE",

	// OTHER CONSTANTS
  CONTENT_DISTINCTIVE: "CONTENT",
  UTILITY_DISTINCTIVE: "UTILITY",
  QUALITY_DISTINCTIVE: "QUALITY",
  EFFICACY_DISTINCTIVE: "EFFICACY",
  START_DISTINCTIVE: "START"
};

export default C;